### PR TITLE
Updates NUnit to 3.6.1

### PR DESCRIPTION
**Pull request by conniey**
* Updates project to run tests against NUnit3.  NUnit 3 supports .NET Core, so this PR is one of a few to support RazorEngine on .NET Core.

**Question**
When I first run the project by executing:
1. `.paket\paket.bootstrapper.exe` (The version it downloads is Paket 4.8.4)
2. `.paket\paket.exe install`

I get:
```
Paket failed with:

Installation Errors :
Package Microsoft.AspNet.Razor is referenced in different versions in D:\git\conniey\RazorEngine\src\source\RazorEngine.Core\RazorEngine.Core.csproj (2.0.30506 vs 3.2.3), check the lock-file.
```
Is this error expected?  

When I ran `paket.exe install` after updating the NUnit references, I thought it would modify the test projects with the new dependencies.  However, it didn't, so I had to do it by hand so that it worked.  Is this the expected behaviour? :/  Am I missing a step?

### CODE REVIEW

**Comment by matthid** [comment]
Will take a look as soon as I can (to answer your questions).. Thanks for this

**Comment by conniey** [comment]
@matthid Hi, any updates on that paket install issue? I am trying to migrate the the solution to .NET Core but I keep running into this problem and don't want to migrate NuGet v3, undoing your work (unless you're OK with that).

**Comment by matthid** [comment]
Ok its even worse imho. Its a regular paket bug that got introduced quite some time ago :/

**Comment by matthid** [comment]
Related bug: https://github.com/fsprojects/Paket/issues/1458

**Comment by agross** [comment]
FYI, the the new NUnit version constraint limits you to 3.6.x. Usually you would limit yourself to 3.x with `~> 3.6` in the dependencies file.

**Comment by matthid** [comment]
Regarding the paket bug: One "workaround" would be to finally drop net40 support... But let me first try to get the paket fix through the door. 

@agross can you comment there and let me know what you think about the warning? (If it's not ok I'd rather remove the warning for now, release the fix and discuss the warning in a separate PR)

**Comment by agross** [comment]
@matthid I'm OK with the warning message.

The original report (https://github.com/fsprojects/Paket/issues/1458) stemmed from my (mis-)use of groups in Paket. Being a heavy bundler user I thought I could use groups as categorization mechanism without knowing that Paket uses groups as a dependency resolution scope. In bundler, groups are used to e.g. reduce the number of dependencies that are installed in production, where test libraries are most often not required. So, yes, we should discourage this use-case in Paket.

**Comment by matthid** [comment]
@conniey Sorry I forgot to notify you but it should work again with latest paket releases (>=5.0.0-beta005).

**Comment by conniey** [comment]
Thanks for getting this fixed!  I got it to work when I was using 5.0.0-beta010... To fix the CI builds, I had to update the build.cmd/build.sh to set the PAKET_VERSION environment variable. Is this PR okay now?

**Comment by matthid** [comment]
Yep looks good, thank you!

**Pull request merged**
