### PR TITLE
added TryRemoveTemplate to ICachingProvider

### PR DESCRIPTION
**Pull request by vurt007**
I had to implement this to allow flushing of cached templates, In my solution I am monitoring the razor templates  with filewatchers and flushing the cache when the files change

### CODE REVIEW

**Comment by matthid** [comment]
Thanks for the contribution!
Is there a reason to not implement the filewatcher within a custom implementation of ICachingProvider (without the need to change the current interface)?

I actually didn't include `TryRemoveTemplate` by design. The reasoning is the following:
- Removing things from the cache is basically a memory leak.
- Doing memory leaks should hurt (and not be a simple call to the caching provider)

The design idea to do what you suggest here is the following:
- Implement your own `ICachingProvider` which can delete templates (maybe we should provide that with a HUGE Warning flag)
- Implement an `ITemplateManager` which watches files, takes the `CachingProvider` in its constructor and notifies the cache when something changes (maybe we should have an example in the documentation?).

But maybe I didn't think far enough, what would you say? And how do you use this? Are you aware of the memory leak you introduced?

**Comment by vurt007** [comment]
Hi Matthid

I think what I tried to do was effectively an implementation of what you have described "Implement an ITemplateManager which watches files, takes the CachingProvider in its constructor and notifies the cache when something changes (maybe we should have an example in the documentation?)."

The question was "how to notify the cache when something changes", ideally without implementing my own caching provider. The documentation for the ITemplateManager mentions caching within the template manager, but public ITemplateSource Resolve(ITemplateKey key) only gets called when ICachingProvider is a cache miss, to implement cache flushing on template change, then a custom template provider and cache provider are required. I take your point on memory leaks regarding the in generated page classes etc, though in production it is unlikely that templates would be changing very often. I see this more as a 'dev time' feature to change templates and see instant results without restarting.  I guess same problem exists for classic ASP / MVC / Razor template managers, re not being able to clean up generated classes without unloading the appDomain ?

Matt

**Comment by matthid** [comment]
So ultimately we agree that we want to have https://github.com/Antaris/RazorEngine/issues/250#issuecomment-78453226? 

>  The documentation for the ITemplateManager mentions caching within the template manager, but public ITemplateSource Resolve(ITemplateKey key) only gets called when ICachingProvider is a cache miss, to implement cache flushing on template change, then a custom template provider and cache provider are required. I take your point on memory leaks regarding the in generated page classes etc, 

Yes this is by design and a feature,

> though in production it is unlikely that templates would be changing very often. 

There where real issues (which are the reason for the current API design) and sadly people will use this for the wrong reasons once it's in the public API. 

> I see this more as a 'dev time' feature to change templates and see instant results without restarting.

This was requested quite a few times, so maybe I can finally tackle #250 once I have some spare time. For now it's up-for-grabs ...
I think having a `InvalidatingCachingProvider` implementation with a huge warning sign and docs stating it shouldn't be used in production is the correct way forward (even when they seem to be a bit more work)

**Comment by vurt007** [comment]
sure #250 should do the trick too ...  sounds very similar to my current implementation, thanks for looking at this

**Pull request closed without merging**
