### PR TITLE
Fix NuGet package for 4.5.1-alpha

### LINKED ISSUE #485: [4.5.1-alpha001] FileNotFoundException: Could not load file or assembly 'Microsoft.CodeAnalysis
After updating to the latest version my call now fails with

```
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.CodeAnalysis, Version=1.3.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
         File name: 'Microsoft.CodeAnalysis, Version=1.3.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
            at RazorEngine.Roslyn.CSharp.RoslynCompilerServiceBase.CompileType(TypeContext context)
            at RazorEngine.Templating.RazorEngineCore.CreateTemplateType(ITemplateSource razorTemplate, Type modelType)
            at RazorEngine.Templating.RazorEngineCore.Compile(ITemplateKey key, Type modelType)
            at RazorEngine.Templating.RazorEngineService.CompileAndCacheInternal(ITemplateKey key, Type modelType)
            at RazorEngine.Templating.RazorEngineService.GetCompiledTemplate(ITemplateKey key, Type modelType, Boolean compileOnCacheMiss)
            at RazorEngine.Templating.RazorEngineService.RunCompile(ITemplateKey key, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
            at RazorEngine.Templating.DynamicWrapperService.RunCompile(ITemplateKey key, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
            at RazorEngine.Templating.RazorEngineServiceExtensions.<>c__DisplayClass16_0.<RunCompile>b__0(TextWriter writer)
            at RazorEngine.Templating.RazorEngineServiceExtensions.WithWriter(Action`1 withWriter)
            at RazorEngine.Templating.RazorEngineServiceExtensions.RunCompile(IRazorEngineService service, String name, Type modelType, Object model, DynamicViewBag viewBag)
```

I haven't looked too deeply at this, but the only thing that may be missing is a dependency:

image

Downgrading to __4.5.0-rc1__ seems to have fixed this, but I haven't started actually verifying it.

### LINKED ISSUE #486: Not compatible with Microsoft.AspNetCore.Razor 2.0.0
[Microsoft.AspNetCore.Razor 2.0.0](https://www.nuget.org/packages/Microsoft.AspNetCore.Razor/2.0.0) only contains a netstandard2.0 dll with a few types:

image

This obviously causes RazorEngine to crash.

I would suggest to change the reference to 1.0 <= x < 2.0 and/or inquire with the asp.net team if this was on purpose and where the types moved.

### PR DESCRIPTION
**Pull request by conniey**
* Adds missing dependencies for the NuGet package
* Requires exact version of Microsoft.AspNetCore.Razor
   * See https://github.com/aspnet/Razor/issues/1855#issuecomment-352846900 for context

I uploaded the package to this NuGet feed so you can test that the package restores and test its functionality.

MyGet Feed: https://www.myget.org/F/razorengine-test/api/v3/index.json
PackageId: RazorEngine 4.5.1-alpha003

Fixes #485. Fixes #486.

### CODE REVIEW

**Comment by conniey** [comment]
Hey @matthid , I apologise for not getting back to you on this. Have you been able to verify this?

**Comment by chlowell** [comment]
@matthid This fixes dependency issues I encountered with `4.5.1-alpha001`. Is there a timeline for another release?

**Comment by conniey** [comment]
@matthid @chlowell and I tested this on our service and with these dependencies the package works. Is it possible to merge, and update the one on NuGet?

**Comment by matthid** [comment]
Thanks, sorry for taking a while. @conniey would you be interested in helping to maintain this project? You can ping me on Skype `matthi <dot> d @ live <dot> de` if you want.

**Comment by coderabsolute** [comment]
`4.5.1-alpha003` is not yet available on NuGet?

**Comment by DoCode** [comment]
@coderabsolute only on the MyGet Feed: https://www.myget.org/F/razorengine-test/api/v3/index.json

**Pull request merged**
