### PR TITLE
fix vb.net generic type parameter list

### LINKED ISSUE #337: VB.NET, RunCompile generates incorrect code when the model is generic
Hello,

I am getting some errors when attempting to call RunCompile with a List as the model.  It seems that the template's auto-generated code is missing a space in the type parameter.

The code generated that causes the error (note the lack of a space between "Of" and "ModelType"):
````VB.NET
Public Class RazorEngine_c8e74c56aa484de2bf2a23e17050a222
        Inherits RazorEngine.Templating.TemplateBase(Of System.Collections.Generic.List(OfModelType))
````

Thanks,
Paul

### PR DESCRIPTION
**Pull request by campersau**
fixes #337 

Just saw this and fixed it with github edit, so no tests at the moment.

### CODE REVIEW

**Comment by campersau** [comment]
Test added.

**Comment by matthid** [comment]
Thanks. How did that go unnoticed for so long oO.

**Comment by matthid** [comment]
Released in https://www.nuget.org/packages/RazorEngine/3.8.2

**Comment by campersau** [comment]
Just for reference: the bug was introduced with https://github.com/Antaris/RazorEngine/commit/bc1fc431353669c8e9852e4de16c17f0649c6de7 in https://github.com/Antaris/RazorEngine/pull/110 on 26 Jun 2013.

**Pull request merged**
