### PR TITLE
Template Run performance optimizations

### PR DESCRIPTION
**Pull request by RoboBurned**
This patch returns back StringBuilder usage as was in older versions.
Casting with "as" was replaced with check by "is" operator.
Do not perform slow attribute inspection if passed model is not of type "object".
Related issue: https://github.com/Antaris/RazorEngine/issues/327

### CODE REVIEW

**Comment by matthid** [comment]
Thanks! LGTM, did you test that this solves your performance issue? Maybe we should add performance tests so that we don't run into this again. Any idea? If you are blocked by this (and need a new release 'right now') I can merge, test and release this without tests.

**Comment by matthid** [comment]
Released in https://www.nuget.org/packages/RazorEngine/3.7.3

**Comment by RoboBurned** [comment]
Thank you for quick release. I repeated the original tests from the issue and see 11s on old version and only 9s on new so I thinks it is good news and the issue can be closed.
I am not expert in tests. We can't just parse some sample template and expect the time to be less than x because it will vary on different computers. One possible solution can be a separate executable that will perform some tests and print out results in a way that is easy to compare. Then one have to run this on different builds and see the changes by hand or by compare tool.

**Comment by matthid** [comment]
> than x because it will vary on different computers

Yes exactly :(. Well, then, I hope someone complains again the next time the performance drops :+1: . Thanks again for the patch.

**Pull request merged**
