### PR TITLE
Non-Caching "Parse" method

### PR DESCRIPTION
**Pull request by SharpeRAD**
While I love the new caching features you've introduced there are times where I want to run a template without caching against a service that contains cached templates (areas).

### CODE REVIEW

**Comment by SharpeRAD** [comment]
PS: Check out [Cake](https://github.com/cake-build/cake) you're build process will never be the same :smile:

**Comment by matthid** [comment]
Thanks, the problem I see with this is that the assembly is basically still cached in memory its just that you remove the possibility to access it (easily at least). This is basically a hidden memory leak.

Cake looks nice (thanks for the hint!), but it actually looks pretty much like a FAKE copy (which it what we are using currently) so I don't really see `the` reason to switch (for this project at least). And FAKE seems to be better integrated in a lot of tools we are currently using for building (Paket, FSharp.Formatting,... ). And Cake looks (from my first impression) quite limited (load custom assemblies?, open custom namespaces?, define custom types?) compared to FAKE.

**Comment by SharpeRAD** [comment]
Can point me in the right direction of where to look for the cached assembly as I really need this feature?

**Comment by matthid** [comment]
The problem is a CLR limitation, you can not unload a single assembly. You can only unload complete AppDomains. The assembly is loaded here: https://github.com/Antaris/RazorEngine/blob/master/src/source/RazorEngine.Core/Compilation/DirectCompilerServiceBase.cs#L264

WIthout loading the assembly you cannot run the template...

**Comment by matthid** [comment]
If you need this and are fine with increasing memory usage you can manually delete the cache entries (use the `InvalidatingCachingProvider` and a custom `TemplateManger` without internal caching, like https://github.com/Antaris/RazorEngine/blob/master/src/source/RazorEngine.Core/Templating/ResolvePathTemplateManager.cs)

On the other hand of you are fine with weak performance but don't want memory leaks you can spin up a new `IsolatedRazorEngineService` instance and destroy the new `AppDomain` when you are finished

**Pull request closed without merging**
