### PR TITLE
Switch to paket groups instead of NuGet hack.

### PR DESCRIPTION
**Pull request by matthid**
- Switch to latest paket (2.0) with groups (prerelease)
- Remove NuGet and set UseNuget to false (this simplifies updating in the future)
- Update to latest Razor4-beta7

### CODE REVIEW

**Comment by mikeandersun** [comment]
Can we use it with ASP.NET 5 now?

**Comment by matthid** [comment]
@mikeandersun You should be able to use the latest 4.x alpha release with ASP.NET 5.

**Comment by mikeandersun** [comment]
I try 4.2.2 beta1 .But didn't work.
Is the any plan to this matter?

**Comment by matthid** [comment]
how does it not work? Can you make sure to use the correct `Microsoft.AspNet.Razor` 4 Version (beta6) in your `project.json`?

**Comment by mikeandersun** [comment]
the Error	is:
The dependency RazorEngine 4.2.1-beta1 in project 'xyz' does not support framework DNXCore,Version=v5.0.

**Pull request merged**
